import type { ChineseZodiac } from './mystic-report-types'

export const chineseZodiacData: { [key: number]: ChineseZodiac } = {
  0: {
    animal: 'Macaco',
    element: 'Metal',
    yinYang: 'Yang',
    traits: ['Inteligente', 'Criativo', 'Versátil', 'Esperto', 'Sociável'],
    compatibility: ['Rato', 'Dragão'],
    loveCompatibility: ['Rato', 'Dragão'],
    careerCompatibility: ['Rato', 'Serpente'],
    luckyNumbers: [4, 9],
    luckyColors: ['Dourado', 'Branco'],
    careerAdvice: ['Tecnologia', 'Comunicação', 'Vendas', 'Entretenimento'],
    relationshipTips: ['Busque parceiros intelectuais', 'Valorize a liberdade', 'Comunique-se abertamente'],
    challenges: ['Impaciência', 'Superficialidade', 'Inquietação'],
    strengths: ['Adaptabilidade', 'Inteligência', 'Carisma']
  },
  1: {
    animal: 'Galo',
    element: 'Metal',
    yinYang: 'Yin',
    traits: ['Corajoso', 'Honesto', 'Trabalhador', 'Pontual', 'Organizado'],
    compatibility: ['Boi', 'Serpente'],
    loveCompatibility: ['Boi', 'Serpente'],
    careerCompatibility: ['Dragão', 'Serpente'],
    luckyNumbers: [5, 7, 8],
    luckyColors: ['Dourado', 'Marrom'],
    careerAdvice: ['Administração', 'Militar', 'Agricultura', 'Contabilidade'],
    relationshipTips: ['Seja direto e honesto', 'Valorize a lealdade', 'Mantenha rotinas'],
    challenges: ['Crítica excessiva', 'Perfeccionismo', 'Teimosia'],
    strengths: ['Honestidade', 'Determinação', 'Organização']
  },
  2: {
    animal: 'Cão',
    element: 'Terra',
    yinYang: 'Yang',
    traits: ['Leal', 'Responsável', 'Confiável', 'Justo', 'Protetor'],
    compatibility: ['Tigre', 'Coelho'],
    loveCompatibility: ['Tigre', 'Cavalo'],
    careerCompatibility: ['Coelho', 'Tigre'],
    luckyNumbers: [3, 4, 9],
    luckyColors: ['Verde', 'Vermelho'],
    careerAdvice: ['Direito', 'Segurança', 'Serviço Social', 'Veterinária'],
    relationshipTips: ['Construa confiança gradualmente', 'Seja fiel', 'Proteja quem ama'],
    challenges: ['Pessimismo', 'Ansiedade', 'Desconfiança'],
    strengths: ['Lealdade', 'Justiça', 'Proteção']
  },
  3: {
    animal: 'Porco',
    element: 'Terra',
    yinYang: 'Yin',
    traits: ['Generoso', 'Compassivo', 'Diligente', 'Honesto', 'Otimista'],
    compatibility: ['Coelho', 'Cabra'],
    loveCompatibility: ['Cabra', 'Coelho'],
    careerCompatibility: ['Tigre', 'Cabra'],
    luckyNumbers: [2, 5, 8],
    luckyColors: ['Amarelo', 'Cinza'],
    careerAdvice: ['Gastronomia', 'Hospitalidade', 'Finanças', 'Arte'],
    relationshipTips: ['Seja generoso com afeto', 'Valorize a harmonia', 'Cultive a paciência'],
    challenges: ['Ingenuidade', 'Materialismo', 'Indulgência'],
    strengths: ['Generosidade', 'Honestidade', 'Compaixão']
  },
  4: {
    animal: 'Rato',
    element: 'Metal',
    yinYang: 'Yang',
    traits: ['Inteligente', 'Adaptável', 'Charmoso', 'Ambicioso', 'Sociável'],
    compatibility: ['Dragão', 'Macaco'],
    loveCompatibility: ['Dragão', 'Macaco'],
    careerCompatibility: ['Boi', 'Macaco'],
    luckyNumbers: [2, 3],
    luckyColors: ['Azul', 'Dourado'],
    careerAdvice: ['Negócios', 'Política', 'Escritor', 'Pesquisador'],
    relationshipTips: ['Use seu charme natural', 'Seja adaptável', 'Mantenha-se interessante'],
    challenges: ['Oportunismo', 'Ganância', 'Inquietação'],
    strengths: ['Inteligência', 'Adaptabilidade', 'Charme']
  },
  5: {
    animal: 'Boi',
    element: 'Metal',
    yinYang: 'Yin',
    traits: ['Determinado', 'Confiável', 'Forte', 'Paciente', 'Metódico'],
    compatibility: ['Serpente', 'Galo'],
    loveCompatibility: ['Rato', 'Serpente'],
    careerCompatibility: ['Galo', 'Serpente'],
    luckyNumbers: [1, 9],
    luckyColors: ['Azul', 'Amarelo'],
    careerAdvice: ['Agricultura', 'Construção', 'Medicina', 'Engenharia'],
    relationshipTips: ['Seja consistente', 'Demonstre estabilidade', 'Valorize tradições'],
    challenges: ['Teimosia', 'Lentidão', 'Conservadorismo'],
    strengths: ['Determinação', 'Confiabilidade', 'Paciência']
  },
  6: {
    animal: 'Tigre',
    element: 'Madeira',
    yinYang: 'Yang',
    traits: ['Corajoso', 'Competitivo', 'Imprevisível', 'Carismático', 'Independente'],
    compatibility: ['Cavalo', 'Cão'],
    loveCompatibility: ['Cavalo', 'Cão'],
    careerCompatibility: ['Dragão', 'Cavalo'],
    luckyNumbers: [1, 3, 4],
    luckyColors: ['Azul', 'Cinza'],
    careerAdvice: ['Liderança', 'Esportes', 'Aventura', 'Empreendedorismo'],
    relationshipTips: ['Mantenha a paixão viva', 'Respeite a independência', 'Seja aventureiro'],
    challenges: ['Impulsividade', 'Rebeldia', 'Impaciência'],
    strengths: ['Coragem', 'Liderança', 'Carisma']
  },
  7: {
    animal: 'Coelho',
    element: 'Madeira',
    yinYang: 'Yin',
    traits: ['Gentil', 'Elegante', 'Responsável', 'Diplomático', 'Artístico'],
    compatibility: ['Cabra', 'Porco'],
    loveCompatibility: ['Cabra', 'Porco'],
    careerCompatibility: ['Cão', 'Porco'],
    luckyNumbers: [3, 4, 6],
    luckyColors: ['Rosa', 'Vermelho'],
    careerAdvice: ['Arte', 'Diplomacia', 'Moda', 'Decoração'],
    relationshipTips: ['Cultive a elegância', 'Seja diplomático', 'Crie ambientes harmoniosos'],
    challenges: ['Superficialidade', 'Indecisão', 'Pessimismo'],
    strengths: ['Diplomacia', 'Elegância', 'Sensibilidade']
  },
  8: {
    animal: 'Dragão',
    element: 'Terra',
    yinYang: 'Yang',
    traits: ['Confiante', 'Inteligente', 'Entusiasmado', 'Carismático', 'Ambicioso'],
    compatibility: ['Rato', 'Macaco'],
    loveCompatibility: ['Rato', 'Macaco'],
    careerCompatibility: ['Galo', 'Rato'],
    luckyNumbers: [1, 6, 7],
    luckyColors: ['Dourado', 'Prata'],
    careerAdvice: ['Liderança', 'Política', 'Entretenimento', 'Inovação'],
    relationshipTips: ['Seja magnético', 'Inspire outros', 'Mantenha o mistério'],
    challenges: ['Arrogância', 'Impaciência', 'Dominação'],
    strengths: ['Carisma', 'Liderança', 'Visão']
  },
  9: {
    animal: 'Serpente',
    element: 'Fogo',
    yinYang: 'Yin',
    traits: ['Sábio', 'Intuitivo', 'Misterioso', 'Elegante', 'Filosófico'],
    compatibility: ['Boi', 'Galo'],
    loveCompatibility: ['Boi', 'Galo'],
    careerCompatibility: ['Macaco', 'Galo'],
    luckyNumbers: [2, 8, 9],
    luckyColors: ['Vermelho', 'Amarelo'],
    careerAdvice: ['Filosofia', 'Psicologia', 'Medicina', 'Pesquisa'],
    relationshipTips: ['Cultive o mistério', 'Seja profundo', 'Use sua intuição'],
    challenges: ['Desconfiança', 'Possessividade', 'Frieza'],
    strengths: ['Sabedoria', 'Intuição', 'Profundidade']
  },
  10: {
    animal: 'Cavalo',
    element: 'Fogo',
    yinYang: 'Yang',
    traits: ['Energético', 'Independente', 'Alegre', 'Aventureiro', 'Sociável'],
    compatibility: ['Tigre', 'Cão'],
    loveCompatibility: ['Tigre', 'Cão'],
    careerCompatibility: ['Cabra', 'Tigre'],
    luckyNumbers: [2, 3, 7],
    luckyColors: ['Amarelo', 'Verde'],
    careerAdvice: ['Viagens', 'Esportes', 'Comunicação', 'Vendas'],
    relationshipTips: ['Mantenha a liberdade', 'Seja espontâneo', 'Compartilhe aventuras'],
    challenges: ['Inconstância', 'Impaciência', 'Egoísmo'],
    strengths: ['Energia', 'Liberdade', 'Otimismo']
  },
  11: {
    animal: 'Cabra',
    element: 'Terra',
    yinYang: 'Yin',
    traits: ['Gentil', 'Compassivo', 'Artístico', 'Pacífico', 'Intuitivo'],
    compatibility: ['Coelho', 'Porco'],
    loveCompatibility: ['Coelho', 'Porco'],
    careerCompatibility: ['Cavalo', 'Porco'],
    luckyNumbers: [3, 9, 4],
    luckyColors: ['Verde', 'Vermelho'],
    careerAdvice: ['Arte', 'Terapia', 'Jardinagem', 'Música'],
    relationshipTips: ['Seja carinhoso', 'Cultive a paz', 'Expresse criatividade'],
    challenges: ['Pessimismo', 'Dependência', 'Indecisão'],
    strengths: ['Criatividade', 'Compaixão', 'Intuição']
  }
}

export const astrologySigns = {
  'Áries': {
    element: 'Fogo',
    quality: 'Cardeal',
    ruler: 'Marte',
    traits: ['Corajoso', 'Impulsivo', 'Líder'],
    description: 'Pioneiro natural, iniciador de projetos, energia dinâmica',
    challenges: ['Impaciência', 'Impulsividade', 'Egocentrismo'],
    advice: 'Canalize sua energia em projetos construtivos e pratique paciência'
  },
  'Touro': {
    element: 'Terra',
    quality: 'Fixo',
    ruler: 'Vênus',
    traits: ['Estável', 'Sensual', 'Determinado'],
    description: 'Busca segurança e estabilidade, aprecia prazeres da vida',
    challenges: ['Teimosia', 'Materialismo', 'Resistência à mudança'],
    advice: 'Cultive flexibilidade e abra-se para novas experiências'
  },
  'Gêmeos': {
    element: 'Ar',
    quality: 'Mutável',
    ruler: 'Mercúrio',
    traits: ['Comunicativo', 'Versátil', 'Curioso'],
    description: 'Mente ágil, comunicador nato, busca variedade e conhecimento',
    challenges: ['Dispersão', 'Superficialidade', 'Inconstância'],
    advice: 'Foque em aprofundar conhecimentos e desenvolva consistência'
  },
  'Câncer': {
    element: 'Água',
    quality: 'Cardeal',
    ruler: 'Lua',
    traits: ['Emotivo', 'Protetor', 'Intuitivo'],
    description: 'Altamente intuitivo, protetor da família, emocionalmente profundo',
    challenges: ['Mau humor', 'Possessividade', 'Insegurança'],
    advice: 'Desenvolva autoconfiança e pratique desapego emocional'
  },
  'Leão': {
    element: 'Fogo',
    quality: 'Fixo',
    ruler: 'Sol',
    traits: ['Criativo', 'Generoso', 'Dramático'],
    description: 'Criativo e expressivo, busca reconhecimento e admiração',
    challenges: ['Arrogância', 'Egocentrismo', 'Drama excessivo'],
    advice: 'Pratique humildade e use sua criatividade para inspirar outros'
  },
  'Virgem': {
    element: 'Terra',
    quality: 'Mutável',
    ruler: 'Mercúrio',
    traits: ['Analítico', 'Prático', 'Perfeccionista'],
    description: 'Detalhista e organizado, busca perfeição e eficiência',
    challenges: ['Crítica excessiva', 'Preocupação', 'Perfeccionismo'],
    advice: 'Aceite imperfeições e pratique autocompaixão'
  },
  'Libra': {
    element: 'Ar',
    quality: 'Cardeal',
    ruler: 'Vênus',
    traits: ['Diplomático', 'Harmonioso', 'Justo'],
    description: 'Busca equilíbrio e harmonia, diplomata natural',
    challenges: ['Indecisão', 'Dependência', 'Superficialidade'],
    advice: 'Desenvolva autoconfiança e tome decisões independentes'
  },
  'Escorpião': {
    element: 'Água',
    quality: 'Fixo',
    ruler: 'Plutão',
    traits: ['Intenso', 'Transformador', 'Misterioso'],
    description: 'Profundo e transformador, busca verdades ocultas',
    challenges: ['Possessividade', 'Ciúme', 'Vingança'],
    advice: 'Pratique perdão e use sua intensidade para transformação positiva'
  },
  'Sagitário': {
    element: 'Fogo',
    quality: 'Mutável',
    ruler: 'Júpiter',
    traits: ['Aventureiro', 'Filosófico', 'Otimista'],
    description: 'Busca conhecimento e aventura, filosofo natural',
    challenges: ['Exagero', 'Impaciência', 'Falta de tato'],
    advice: 'Pratique moderação e desenvolva sensibilidade social'
  },
  'Capricórnio': {
    element: 'Terra',
    quality: 'Cardeal',
    ruler: 'Saturno',
    traits: ['Ambicioso', 'Disciplinado', 'Responsável'],
    description: 'Ambicioso e disciplinado, busca status e reconhecimento',
    challenges: ['Pessimismo', 'Rigidez', 'Materialismo'],
    advice: 'Cultive otimismo e valorize aspectos emocionais da vida'
  },
  'Aquário': {
    element: 'Ar',
    quality: 'Fixo',
    ruler: 'Urano',
    traits: ['Inovador', 'Independente', 'Humanitário'],
    description: 'Visionário e humanitário, busca inovação e liberdade',
    challenges: ['Frieza', 'Rebeldia', 'Distanciamento'],
    advice: 'Desenvolva intimidade emocional e pratique compaixão pessoal'
  },
  'Peixes': {
    element: 'Água',
    quality: 'Mutável',
    ruler: 'Netuno',
    traits: ['Intuitivo', 'Compassivo', 'Artístico'],
    description: 'Altamente intuitivo e compassivo, conectado ao espiritual',
    challenges: ['Escapismo', 'Confusão', 'Vitimização'],
    advice: 'Desenvolva praticidade e estabeleça limites claros'
  }
}
